iface-modem, novatel-lte: disable network scan in LTE mode
BUG=chrome-os-partner:17055
TEST=`mmcli -m 0 --3gpp-scan` returns the following error:

  error: couldn't scan networks in the modem:
  'GDBus.Error:org.freedesktop.ModemManager1.Error.Core.Unsupported:
  Couldn't scan for networks with access technologies: lte'

(cherry picked from commit e93922197522067851f8cb4b7948ecae93e2843c)

Change-Id: Ic7b25ca212dd0397b18621fc77def0877ee63de0
Reviewed-on: https://gerrit.chromium.org/gerrit/41503
Commit-Queue: Ben Chan <benchan@chromium.org>
Reviewed-by: Ben Chan <benchan@chromium.org>
Tested-by: Ben Chan <benchan@chromium.org>