UPSTREAM: fibocom: disable multiplexing support in NL668
The NL668 doesn't seem to support multiplexing, as it fails to
transfer data even in the one multiplexed PDN case.

(cherry picked from commit 50caac4bdd679eada5002c0b5da93a52b26f239a)

BUG=b:294648017
TEST=Manual connection attempts

   # mmcli -m a --simple-connect="multiplex=required,apn=broadband,ip-type=ipv4v6,apn-type=default"
   error: couldn't connect the modem: 'GDBus.Error:org.freedesktop.ModemManager1.Error.Core.Unsupported: Invalid bearer properties: Multiplexing required but not supported'

   # mmcli -m a --simple-connect="multiplex=requested,apn=broadband,ip-type=ipv4v6,apn-type=default"
   successfully connected the modem

   # mmcli -b 1
     ------------------------------------
     Status             |      connected: yes
                        |      suspended: no
                        |    multiplexed: no
                        |      interface: wwan0       <----- Not multiplexed
                        |     ip timeout: 20

Change-Id: I61a50f23918ce6e4be06d1cb43af3b0d8c99ce8b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/modemmanager-next/+/4753098
Auto-Submit: Aleksander Morgado <aleksandermj@google.com>
Tested-by: Aleksander Morgado <aleksandermj@google.com>
Reviewed-by: Andrew Lassalle <andrewlassalle@chromium.org>
Commit-Queue: Andrew Lassalle <andrewlassalle@chromium.org>