CHROMIUM: fibocom: disable multiplexing in the FM350
Firmware version 81600.0000.00.29.19.16 of the FM350 supports one
single multiplexed PDN session in most operators, but it fails in
Verizon even with one.

Flag the device as not supporting any multiplexing for now.

BUG=b:236295106
TEST=Manual connection attempts

   # mmcli -m a --simple-connect="multiplex=required,apn=internet,ip-type=ipv4v6,apn-type=default"
   error: couldn't connect the modem: 'GDBus.Error:org.freedesktop.ModemManager1.Error.Core.Unsupported: Invalid bearer properties: Multiplexing required but not supported'

   # mmcli -m a --simple-connect="multiplex=requested,apn=internet,ip-type=ipv4v6,apn-type=default"
   successfully connected the modem

   # mmcli -b 1
     ------------------------------------
     Status             |      connected: yes
                        |      suspended: no
                        |    multiplexed: no
                        |      interface: wwan0       <----- Not multiplexed
                        |     ip timeout: 20

Change-Id: I71844a487e155999572a26231930e482cbc973fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/modemmanager-next/+/4614548
Commit-Queue: Aleksander Morgado <aleksandermj@google.com>
Tested-by: Aleksander Morgado <aleksandermj@google.com>
Reviewed-by: Andrew Lassalle <andrewlassalle@chromium.org>